version: 2
updates:
  - directory: /
    labels:
      - dependencies
    package-ecosystem: npm
    reviewers:
      - kurone-kito
    assignees:
      - kurone-kito
    schedule:
      interval: monthly
registries:
  npm-github:
    token: ${{ secrets.NPM_TOKEN }}
    type: npm-npmjs
    url: https://registry.npmjs.org
