cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
import:
  - '@kurone-kito/cspell-config'
version: '0.2'
words:
  - dedup
  - deprioritize
  - desync
  - desynced
  - esync
  - GHEC
  - GHES
  - idd
  - isort
  - kito
  - kuron
  - kurone
  - kuroné
  - minimizable
  - ministral
  - npms.io
  - nvmrc
  - onnx
  - pylint
  - pyproject
  - pytest
  - qwen
  - rollup
  - toctou
  - tsfile
  - unconverged
  - undispositioned
  - unioned
  - unmigrated
  - unmirrored
  - unpushed
  - unreplied
  - unrouted
  - unscored
  - unwaived
  - waivable
  - WHATWG
