allowBuilds:
  '@kurone-kito/idd-skill@https://codeload.github.com/kurone-kito/idd-skill/tar.gz/f16660486383ce710a0f33f49aa3331ddece93de': true
gitChecks: false
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
onlyBuiltDependencies:
  - '@biomejs/biome'
  - es5-ext
