allowBuilds:
  '@kurone-kito/idd-skill@https://codeload.github.com/kurone-kito/idd-skill/tar.gz/1f90787ebf4021673ce6e5eb69741df331fd2037': true
gitChecks: false
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
onlyBuiltDependencies:
  - '@biomejs/biome'
  - es5-ext
pmOnFail: ignore
