name: CI/CD on master branch
on:
  push:
    branches:
      - master
permissions:
  contents: read
  packages: write
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      INVALID_DUMMY_TOKEN: invalid-token
    steps:
      - uses: actions/checkout@v2
      - name: Use the specified version of Node.js
        uses: actions/setup-node@v2
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version-file: .node-version
      - name: set npm config
        run: npm config set unsafe-perm true
      - name: Resolve the dependencies
        run: npm ci
      - name: Build and release for NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          dry-run: ${{ !!env.ACT }}
          token: ${{ !env.ACT && secrets.NPM_TOKEN || env.INVALID_DUMMY_TOKEN }}
      - name: Build and release for GitHub Registry
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          dry-run: ${{ !!env.ACT }}
          registry: https://npm.pkg.github.com
          token: ${{ !env.ACT && secrets.GITHUB_TOKEN || env.INVALID_DUMMY_TOKEN }}
