name: CI on push the feature branches
on:
  push:
    branches:
      - '*'
      - '!master'
permissions:
  contents: read
jobs:
  build:
    name: Build the production code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x
          - 19.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: ${{ matrix.node-version }}
      - name: set npm config
        run: npm config set unsafe-perm true
      - name: Resolve the dependencies
        run: npm ci
      - name: Build
        run: npm pack
