name: Publish the packages
on:
  release:
    types:
      - published
permissions:
  contents: read
  packages: write
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      INVALID_DUMMY_TOKEN: invalid-token
    steps:
      - name: Stages the pushed branch
        uses: actions/checkout@v7
      - name: Setup the pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Prepare the Node.js environment
        uses: actions/setup-node@v7
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version-file: .node-version
      - name: Resolve the dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and release for NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          access: public
          dry-run: ${{ !!env.ACT }}
          token: ${{ !env.ACT && secrets.NPM_TOKEN || env.INVALID_DUMMY_TOKEN }}
      - name: Build and release for GitHub Registry
        uses: JS-DevTools/npm-publish@v2
        with:
          access: public
          dry-run: ${{ !!env.ACT }}
          registry: https://npm.pkg.github.com
          token: ${{ !env.ACT && secrets.GITHUB_TOKEN || env.INVALID_DUMMY_TOKEN }}
