name: Publish the packages
on:
  release:
    types:
      - published
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Stages the pushed branch
        uses: actions/checkout@v7
      - name: Setup the pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Prepare the Node.js environment
        uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version-file: .node-version
      - name: Resolve the dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and release for NPM
        run: pnpm publish --access public --no-git-checks
      - name: Set up the .npmrc for the GitHub Packages registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << EOF > "${HOME}/.npmrc"
          @kurone-kito:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
          EOF
      - name: Build and release for GitHub Registry
        run: pnpm publish --access public --no-git-checks
